脚本文件上传

diff --git a/platform_deployment/scripts/installscript/installglib b/platform_deployment/scripts/installscript/installglib
--- a/platform_deployment/scripts/installscript/installglib
+++ b/platform_deployment/scripts/installscript/installglib
@@ -12,7 +12,7 @@ install_path=$(cd "$(dirname "$0")";cd ..;pwd)
 #step 1:
 #install autoconf 2.69
 #
-echo "start Install autoconf 2.68.."
+echo "start Install autoconf 2.69.."
 echo "start Install autoconf 2.69.." >> $logfile
 
 cd ${install_path}/lib
@@ -60,8 +60,8 @@ cd ${install_path}/lib
 
 if ! tar xJf automake-1.13.4.tar.xz 2>>$logfile
 then
-    echo "tar automake-1.12.4 fail" 
-    echo "tar automake-1.12.4 fail" >> $logfile
+    echo "tar automake-1.13.4 fail" 
+    echo "tar automake-1.13.4 fail" >> $logfile
     exit 1
 fi
 
@@ -69,23 +69,23 @@ fi
 cd automake-1.13.4
 if ! ./configure --prefix=/usr 2>>$logfile 
 then
-    echo "configure automake-1.12.4 fail" 
-    echo "configure automake-1.12.4 fail" >> $logfile
+    echo "configure automake-1.13.4 fail" 
+    echo "configure automake-1.13.4 fail" >> $logfile
     exit 1
 fi
 
 if ! make 2>>$logfile
 then
-    echo "make automake-1.12.4 fail"
-    echo "make automake-1.12.4 fail" >> $logfile
+    echo "make automake-1.13.4 fail"
+    echo "make automake-1.13.4 fail" >> $logfile
     exit 1
 fi
 
 
 if ! make install 2>>$logfile
 then
-    echo "make install automake-1.12.4 fail"
-    echo "make install automake-1.12.4 fail" >> $logfile
+    echo "make install automake-1.13.4 fail"
+    echo "make install automake-1.13.4 fail" >> $logfile
     exit 1
 fi
 
@@ -117,7 +117,7 @@ then
     exit 1
 fi
 
-if !make 2>>$logfile
+if ! make 2>>$logfile
 then
     echo "make glib-2.36.4 fail"
     echo "make glib-2.36.4 fail" >> $logfile
diff --git a/platform_deployment/scripts/installscript/installlibvirt b/platform_deployment/scripts/installscript/installlibvirt
--- a/platform_deployment/scripts/installscript/installlibvirt
+++ b/platform_deployment/scripts/installscript/installlibvirt
@@ -1,14 +1,95 @@
 #!/bin/sh
 #
-#       script to init libvirt
+#     Install Libvirt、Virtinst and init Libvirt
 #
 
+#####################################
+#1.Install Libvirt
+ldconfig
 logfile="/var/log/zhicloud_install.log"
-#install_path="/home/zhicloud/lib"
-install_path=$(cd "$(dirname "$0")";cd ..;pwd)
+install_path="/home/zhicloud/lib"
 
+echo "start Install libvirt.."
+echo "start Install libvirt.." >> $logfile
+
+cd ${install_path}
+if ! tar -zxf libvirt-1.2.11.tar.gz 2>>$logfile
+then
+    echo "tar libvirt packet fail"
+    echo "tar libvirt packet fail" >> $logfile 
+    exit 1
+fi
+
+cd libvirt-1.2.11
+if ! ./configure --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc 2>>$logfile 
+then 
+    echo "configure libvirt packet fail"
+    echo "configure libvirt packet fail" >> $logfile 
+    exit 1
+fi 
+
+if ! make 2>>$logfile
+then 
+    echo "make libvirt fail"
+    echo "make libvirt fail" >> $logfile 
+    exit 1
+fi
+
+if ! make install 2>>$logfile
+then
+    echo "make install libvirt fail"
+    echo "make install libvirt fail" >> $logfile 
+    exit 1      
+fi
+
+echo "install Libvirt success"
+echo "install Libvirt success" >> $logfile
+
+###################################
+#2.Install libvirt-python#
+cd ${install_path}
+if ! tar -zxf libvirt-python-1.2.11.tar.gz 2>>$logfile
+then
+    echo "tar libvirt-python packet fail"
+    echo "tar libvirt-python packet fail" >> $logfile 
+    exit 1
+fi
+cd libvirt-python-1.2.11
+if ! python setup.py install 2>>$logfile
+then 
+    echo "install libvirt-python fail"
+    echo "install libvirt-python fail" >> $logfile 
+    exit 1
+fi 
+
+
+#2.Install Virtinst#
+echo "start Install Virtinst..."
+echo "start Install Virtinst...">> $logfile
+
+cd ${install_path}
+if ! tar -zxf virtinst-0.600.4.tar.gz 2>>$logfile
+then
+    echo "tar virtinst packet fail"
+    echo "tar virtinst packet fail" >> $logfile 
+    exit 1
+fi
+
+cd virtinst-0.600.4
+if ! python setup.py install 2>>$logfile
+then 
+    echo "install Virtinst fail"
+    echo "install Virtinst fail" >> $logfile 
+    exit 1
+fi 
+echo "install Virtinst success"
+echo "install Virtinst success" >> $logfile
+cp /usr/bin/virt* /usr/sbin/
+
+#######################################
+#3.init the libvirt
+ldconfig  #注册service
 echo "init libvirt... "
-
 chkconfig cgconfig on 2>>$logfile
 service cgconfig start 2>>$logfile
 echo "start config vnc&qemu..."
